services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhilipHartmann\TYPO3FluidApi\:
    resource: "../Classes/*"

  PhilipHartmann\TYPO3FluidApi\Middleware\Api:
    public: true
